name: "My action"
description: "Test my action"

inputs: #Para definir parametros (Contexto)
  message: # Nombre del parametro
    description: "The message for print"
    required: true
    default: "Hola"

runs:
  using: "composite" # Action composite para reusar los steps (Agrupa steps)

  steps:
    - name: Hola mundo
      run: echo "Hola ${{ inputs.message }}" #Interpolacion
      shell: bash # Es una directiva para ejecutar comandos
