name: Test Composite Action

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: mis actions
        uses: ./.github/actions/my-actions # De manera automatica detecta el archivo action.yml con uses
        with: # Permite pasar parametro a las acciones
          message: "Brahian"